export const ENDPOINTS = {
  blog: {
    posts: '/api/blog/posts',
    postBySlug: (slug: string) => `/api/blog/posts/${encodeURIComponent(slug)}`,
    recentPosts: '/api/blog/posts/recent',
    search: '/api/blog/posts/search',
    relatedPosts: (slug: string) => `/api/blog/posts/${encodeURIComponent(slug)}/related`,
    categories: '/api/blog/categories',
    tags: '/api/blog/tags',
  },
  portfolio: {
    profile: '/api/portfolio/profile',
    experiences: '/api/portfolio/experiences',
    projects: '/api/portfolio/projects',
    skills: '/api/portfolio/skills',
    education: '/api/portfolio/education',
    locales: '/api/portfolio/locales',
    works: '/api/portfolio/works',
    workById: (id: number) => `/api/portfolio/works/${id}`,
    experienceById: (id: number) => `/api/portfolio/experiences/${id}`,
    projectById: (id: number) => `/api/portfolio/projects/${id}`,
    educationById: (id: number) => `/api/portfolio/education/${id}`,
    profileAll: '/api/portfolio/profile/all',
    profileImage: '/api/portfolio/profile/image',
    profileIcon: '/api/portfolio/profile/icon',
  },
} as const
