export { PROFILE_DATA } from './data/i18n'
export { default as BriefIntroduction } from './ui/brief-introduction'
export { default as Education } from './ui/education'
export { default as PersonalProjects } from './ui/personal-projects'
export { default as ProfileHeader } from './ui/profile-header'
export { default as RecentExperience } from './ui/recent-experience'
export { default as Skills } from './ui/skills'
