import type { editor } from 'monaco-editor'

export const draculaTheme: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6272a4', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'ff79c6' },
    { token: 'string', foreground: 'f1fa8c' },
    { token: 'number', foreground: 'bd93f9' },
    { token: 'type', foreground: '8be9fd', fontStyle: 'italic' },
    { token: 'function', foreground: '50fa7b' },
    { token: 'variable', foreground: 'f8f8f2' },
    { token: 'constant', foreground: 'bd93f9' },
    { token: 'tag', foreground: 'ff79c6' },
    { token: 'attribute.name', foreground: '50fa7b' },
    { token: 'attribute.value', foreground: 'f1fa8c' },
    { token: 'delimiter', foreground: 'f8f8f2' },
    { token: 'meta', foreground: 'f8f8f2' },
    { token: 'markup.heading', foreground: 'bd93f9', fontStyle: 'bold' },
    { token: 'markup.bold', fontStyle: 'bold' },
    { token: 'markup.italic', fontStyle: 'italic' },
    { token: 'markup.list', foreground: '8be9fd' },
    { token: 'markup.inline', foreground: '50fa7b' },
  ],
  colors: {
    'editor.background': '#282a36',
    'editor.foreground': '#f8f8f2',
    'editor.lineHighlightBackground': '#44475a50',
    'editor.selectionBackground': '#44475a',
    'editorCursor.foreground': '#f8f8f2',
    'editorWhitespace.foreground': '#44475a',
    'editorLineNumber.foreground': '#6272a4',
    'editorLineNumber.activeForeground': '#f8f8f2',
    'editor.selectionHighlightBackground': '#44475a50',
    'editorBracketMatch.background': '#44475a',
    'editorBracketMatch.border': '#6272a4',
    'scrollbarSlider.background': '#44475a80',
    'scrollbarSlider.hoverBackground': '#44475aaa',
  },
}
