export {
  useCreateEducation,
  useCreateExperience,
  useCreateLocale,
  useCreateProject,
  useCreateSkill,
  useCreateWork,
  useDeleteEducation,
  useDeleteExperience,
  useDeleteLocale,
  useDeleteProject,
  useDeleteSkill,
  useDeleteWork,
  useEducation,
  useExperiences,
  useLocales,
  useProfile,
  useProjects,
  useSkills,
  useUpdateEducation,
  useUpdateExperience,
  useUpdateProfile,
  useUpdateProject,
  useUpdateSkill,
  useUpdateWork,
  useWork,
  useWorks,
} from './portfolio.queries'
