export const monokaiWinterNight = {
  base: 'vs-dark' as const,
  inherit: true,
  rules: [
    { token: 'comment', foreground: '546575' },
    { token: 'keyword', foreground: 'F92672' },
    { token: 'string', foreground: 'E6DB74' },
    { token: 'number', foreground: 'AE81FF' },
    { token: 'constant', foreground: 'AE81FF' },
    { token: 'type', foreground: '66D9EF', fontStyle: 'italic' },
    { token: 'function', foreground: '2ee252' },
    { token: 'variable', foreground: 'F8F8F2' },
    { token: 'variable.language', foreground: 'FD971F' },
    { token: 'variable.parameter', foreground: 'FD971F', fontStyle: 'italic' },
    { token: 'tag', foreground: 'F92672' },
    { token: 'attribute.name', foreground: '2ee252' },
    { token: 'attribute.value', foreground: 'E6DB74' },
    { token: 'delimiter', foreground: 'F8F8F2' },
    { token: 'storage', foreground: 'F92672' },
    { token: 'storage.type', foreground: '66D9EF', fontStyle: 'italic' },
    { token: 'support.function', foreground: '66D9EF' },
    { token: 'support.type', foreground: '66D9EF', fontStyle: 'italic' },
    { token: 'entity.name.function', foreground: '2ee252' },
    { token: 'entity.name.type', foreground: '2ee252' },
    { token: 'entity.name.tag', foreground: 'F92672' },
    { token: 'markup.heading', foreground: '2ee252', fontStyle: 'bold' },
    { token: 'markup.bold', foreground: '66D9EF', fontStyle: 'bold' },
    { token: 'markup.italic', foreground: '66D9EF', fontStyle: 'italic' },
    { token: 'markup.list', foreground: 'E6DB74' },
    { token: 'markup.inline.raw', foreground: 'FD971F' },
    { token: 'markup.quote', foreground: 'F92672' },
    { token: 'markup.inserted', foreground: '2ee252' },
    { token: 'markup.deleted', foreground: 'F92672' },
    { token: 'markup.changed', foreground: 'E6DB74' },
    { token: 'invalid', foreground: 'F8F8F0' },
  ],
  colors: {
    'editor.background': '#0d121f',
    'editor.foreground': '#cadbeb',
    'editor.lineHighlightBackground': '#131929',
    'editor.selectionBackground': '#232c45',
    'editorCursor.foreground': '#f2f2f2',
    'editorWhitespace.foreground': '#232c45',
    'editorLineNumber.foreground': '#677078',
    'editorLineNumber.activeForeground': '#cadbeb',
    'editor.selectionHighlightBackground': '#232c4550',
    'editorBracketMatch.background': '#232c45',
    'editorBracketMatch.border': '#677078',
    'scrollbarSlider.background': '#232c4580',
    'scrollbarSlider.hoverBackground': '#232c45aa',
    'editorWidget.background': '#0d121f',
    'editorSuggestWidget.background': '#0d121f',
  },
}
